### ISSUE TITLE
Issue with output format

### ISSUE THREAD

**Issue by overthink** [littlemoule/littlemoule#1]
Hi Abid.

There is a problem with the output format of your solution.  Could you please make sure it conforms to the "Output File" described at http://sortable.com/challenge/?

In particular:
- one JSON Result object per line 
- the value of the "listings" field needs to be an array.  Yours is a sequence of objects (invalid json)

Let me know if/when you fix this up and I will take another look. 

Thanks!

Mark (from sortable.com)

**Comment by littlemoule** [comment]
fixed

~cheers

**Comment by littlemoule** [comment]
Hey Mark,

Did the fix work for you? Were the results any useful? I would be curious to know how it did overall since I wrote that program in a day.

Regards,
Abid
